FROM node:22.2.0

WORKDIR /usr/app

COPY package*.json ./

RUN npm cache clean --force
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]


# FROM node:22.2.0 AS build

# WORKDIR /app

# COPY package.json package-lock.json ./
# RUN npm install

# COPY . .

# RUN npm run build

# FROM node:22.2.0

# WORKDIR /app

# COPY --from=build /app ./

# EXPOSE 3000

# CMD ["npm", "run", "start"]