import { Inter } from "next/font/google";
import "./globals.css";
import HeaderMain from "@/components/header";
import FooterMain from "@/components/footer";
import { SessionProvider } from '@/hooks/sessionProvider'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <HeaderMain />
        <SessionProvider route={process.env.REACT_APP_API_URL_CLIENT}>
          {children}
        </SessionProvider>
        <FooterMain />
      </body>
    </html>
  );
}
